- name: install mysql server
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: true

- name: check mysql service is started
  systemd:
    name: mysql
    state: started
    enabled: true

