- name: create directory
  file:
    path: /var/www/mikbotam
    state: directory
    owner: www-data
    group: www-data

- name: extract file mikbotam mysql version
  unarchive:
    src: files/Mikbotam.zip
    dest: /var/www/mikbotam
    owner: www-data
    group: www-data
  when: database == "mod"

- name: extract file mikbotam sqlite version
  unarchive:
    src: files/Mikbotam.sqlite.zip
    dest: /var/www/mikbotam
    owner: www-data
    group: www-data
  when: database == "sqlite"

- name: extract file mikbotam mysql version
  unarchive:
    src: files/Mikbotam.mysql.zip
    dest: /var/www/mikbotam
    owner: www-data
    group: www-data
  when: database == "mysql"

- name: setup virtualhost mikbotam
  template:
    src: mikbotam.conf.j2
    dest: /etc/nginx/conf.d/mikbotam.conf
  register: vhost_mikbotam

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted
  when: vhost_mikbotam.changed

- name: polling configuration
  template:
    src: mikbotam-polling.conf.j2
    dest: /etc/supervisor/conf.d/mikbotam-polling.conf
  register: polling

- name: patch router os v4.44
  template:
    src: routeros_api.class-4.44.php.j2
    dest: /var/www/mikbotam/Api/routeros_api.class.php
    owner: www-data
    group: www-data
  when: ros == "4.44"

- name: patch router os v6.45
  template:
    src: routeros_api.class-4.65.php.j2
    dest: /var/www/mikbotam/Api/routeros_api.class.php
    owner: www-data
    group: www-data
  when: ros == "6.45"

- name: restart supervisor service
  systemd:
    name: supervisor
    state: restarted
  when: polling.changed


- include: mysql-setup.yml

#- include: sqlite-setup.yml
