- name: create user for app
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    priv: '*.*:ALL'
    state: present
  when: database == "mysql"

- name: create database
  mysql_db:
    name: "{{ dbname }}"
    state: import
    target: /var/www/mikbotam/config/Newdatabase.sql
  when: database == "mysql"

- name: copy mysql configuration
  template:
    src: mysql.config.php.j2
    dest: /var/www/mikbotam/config/system.config.php
    owner: www-data
    group: www-data
  when: database == "mysql"

- name: copy mysql configuration
  template:
    src: mysql.config.php.j2
    dest: /var/www/mikbotam/config/system.config.php
    owner: www-data
    group: www-data
  when: database == "mod"
