- hosts: local
  become: yes
  gather_facts: no
  vars_prompt:
    - name: database
      prompt: "silahkan pilih database yang ingin digunakan (mysql/sqlite)"
      private: no
  roles:
    - mikbotam
